# chat_module.py

def get_response(prompt):
    """
    Returns an intelligent general health-related response based on user prompt.
    This simulates a chatbot and can be expanded using an AI model in future.
    """
    prompt = prompt.lower()

    health_responses = {
        "diabetes": "Diabetes symptoms include frequent urination, increased thirst, and fatigue. Monitor your blood sugar regularly and consult a doctor.",
        "headache": "Headaches can be caused by stress or dehydration. Try resting and drinking water. If persistent, consult a doctor.",
        "heart": "For heart health, maintain a balanced diet and exercise. Chest pain may indicate serious issues, seek immediate care.",
        "blood pressure": "To reduce high blood pressure, limit salt, exercise regularly, and manage stress.",
        "cold": "Common cold is usually viral. Rest and stay hydrated.",
        "fever": "Fever is a symptom, not a disease. Stay hydrated and monitor temperature.",
        "cough": "Dry coughs may be due to allergies, while wet coughs can indicate infection.",
        "asthma": "Asthma requires avoiding triggers and using prescribed inhalers.",
        "flu": "Flu includes symptoms like fever, chills, body aches. Rest and fluids help.",
        "allergy": "Avoid known allergens. Antihistamines can provide relief.",
        "anxiety": "Practice deep breathing, meditation, and talk to a therapist if anxiety persists.",
        "depression": "Talk to a professional. Therapy and medication can help.",
        "acne": "Wash face regularly, avoid oily products, and consider dermatological treatments.",
        "back pain": "Maintain good posture, do back exercises, and see a doctor if chronic.",
        "chest pain": "Can be cardiac or muscular. If severe or persistent, seek emergency help.",
        "dizziness": "May be due to low BP, dehydration, or inner ear issues.",
        "ear pain": "Could be ear infection. Use warm compress and consult ENT.",
        "eye strain": "Take breaks from screens and ensure good lighting.",
        "gastritis": "Avoid spicy food, eat light meals, and take antacids.",
        "constipation": "Eat fiber-rich foods and drink plenty of water.",
        "diarrhea": "Stay hydrated. Avoid oily/spicy food.",
        "insomnia": "Maintain sleep hygiene. Avoid caffeine before bed.",
        "joint pain": "May be due to arthritis or injury. Apply heat/cold packs.",
        "knee pain": "Avoid strain, use support and consult orthopedician.",
        "nausea": "Ginger tea or motion-sickness medicine may help.",
        "obesity": "Follow a calorie-controlled diet and regular exercise.",
        "pimples": "Clean skin daily, avoid touching face, and use medicated products.",
        "rash": "May be allergy or infection. Use mild creams and keep area clean.",
        "sore throat": "Gargle with warm salt water, drink warm fluids.",
        "thyroid": "Regular testing and hormone replacement as advised by doctor.",
        "vomiting": "Stay hydrated, rest, and eat bland food.",
        "wheezing": "Could indicate asthma. Use bronchodilators.",
        "ulcer": "Avoid spicy food and take antacids as prescribed.",
        "uti": "Drink water, maintain hygiene, and take antibiotics if prescribed.",
        "hair fall": "Can be due to stress, genetics, or nutrition.",
        "migraine": "Avoid triggers like lights and caffeine, use prescribed medication.",
        "eczema": "Moisturize regularly and avoid allergens.",
        "psoriasis": "Autoimmune skin condition. Follow dermatological treatment.",
        "liver": "Avoid alcohol and fatty foods. Do regular liver function tests.",
        "kidney": "Monitor creatinine levels and drink enough water.",
        "pregnancy": "Regular checkups, supplements, and avoid stress.",
        "pcos": "Manage with exercise, diet, and hormonal medications.",
        "std": "Practice safe sex, regular screening, and treatment if diagnosed.",
        "hiv": "Get tested, start ART early, and monitor regularly.",
        "covid": "Isolate, monitor oxygen, and consult a doctor.",
        "malaria": "Use mosquito nets, antimalarial medications.",
        "dengue": "Monitor platelet count and hydrate well.",
        "jaundice": "Rest, avoid fatty food, and monitor liver function.",
        "tuberculosis": "Long-term antibiotics and regular monitoring required.",
        "appendicitis": "Sudden pain in lower right abdomen – seek surgery.",
        "hernia": "Requires surgical evaluation.",
        "insulin resistance": "Diet control and exercise help reduce resistance.",
        "glaucoma": "Regular eye exams and pressure-lowering drops.",
        "sinus": "Steam inhalation and avoid cold exposure.",
        "bronchitis": "Avoid smoke, take rest, and use inhalers if needed.",
        "stroke": "FAST check: Face drooping, Arm weakness, Speech difficulty – Time to call emergency.",
        "paralysis": "Physiotherapy and medications as per cause.",
        "fatigue": "Can be due to anemia, thyroid, or sleep disorders.",
        "anemia": "Eat iron-rich foods and take supplements.",
        "fracture": "Immobilize and get X-ray. Follow orthopedic care.",
        "sprain": "RICE: Rest, Ice, Compression, Elevation.",
        "menstrual cramps": "Heat pad and over-the-counter pain relievers help.",
        "infertility": "Both partners need evaluation; many treatment options exist.",
        "vitamin d deficiency": "Sun exposure and supplements help.",
        "bloating": "Avoid carbonated drinks and eat slowly.",
        "autism": "Early therapy helps children develop communication and social skills.",
        "adhd": "Behavioral therapy and medications are often helpful.",
        "arthritis": "Exercise and anti-inflammatory medications help reduce pain.",
        "gout": "Avoid red meat and alcohol. Take medications as prescribed.",
        "dehydration": "Drink plenty of water, especially in heat.",
        "ibs": "Identify food triggers and manage stress.",
        "gerd": "Avoid acidic food and eat smaller meals.",
        "lactose intolerance": "Avoid dairy or use lactase enzymes.",
        "celiac": "Avoid gluten-containing foods.",
        "pneumonia": "Antibiotics, rest, and hydration are key.",
        "sleep apnea": "CPAP device may be needed. Weight loss helps.",
        "nephritis": "Inflammation of kidneys – needs urgent evaluation.",
        "pancreatitis": "Avoid alcohol and fatty foods. Hospitalization may be needed.",
        "thyroid nodules": "Ultrasound and fine-needle aspiration may be required.",
        "fibroids": "May cause heavy bleeding – ultrasound needed.",
        "prostate": "Monitor PSA levels and consult a urologist.",
        "testicular pain": "Could be torsion – emergency attention needed.",
        "breast lump": "Needs clinical exam and mammogram/ultrasound.",
        "menopause": "Hormonal changes – symptoms vary; consult gynecologist.",
        "chickenpox": "Contagious viral infection – isolate and treat symptoms.",
        "measles": "Preventable by vaccination. Seek care for symptoms.",
        "mumps": "Swollen salivary glands – rest and fluids help.",
        "rubella": "Dangerous in pregnancy – ensure vaccination.",
        "hand foot mouth": "Common in children – maintain hygiene.",
        "ringworm": "Fungal infection – use antifungal cream.",
        "scabies": "Itchy skin – use permethrin cream.",
        "lice": "Use medicated shampoo and wash bedding.",
        "pinworm": "Itchy anus – take deworming medicine.",
        "tonsillitis": "Swollen tonsils – salt gargles and antibiotics help.",
        "laryngitis": "Rest voice, hydrate, and avoid irritants.",
        "rsv": "Common in infants – monitor breathing.",
        "bronchiolitis": "Usually viral – keep child hydrated.",
        "hepatitis": "Several types – needs testing and monitoring.",
        "cholera": "Causes diarrhea – rehydration is critical.",
        "typhoid": "Bacterial fever – needs antibiotics and rest.",
        "zika": "Prevent mosquito bites. Risk in pregnancy.",
        "rabies": "Get vaccinated after animal bite immediately.",
        "tetanus": "Keep vaccinations updated. Clean wounds properly.",
        "whooping cough": "Severe cough – treat with antibiotics.",
        "piles": "Eat fiber, avoid straining, and use creams.",
        "fissure": "Warm sitz baths and topical creams help.",
        "fistula": "Needs surgical treatment."
    }

    for key in health_responses:
        if key in prompt:
            return health_responses[key]

    return (
        "That's an important health question! Please consult a healthcare provider for specific advice. "
        "I'm here to help with general medical guidance."
    )
